---
- name: centos_prerequisites | stats dnf
  stat:
    path: /usr/bin/dnf
  register: dnf_binary

- name: centos_prerequisites | install scl repository
  dnf:
    name: centos-release-scl
    state: present

- name: centos_prerequisites | install required packages on centos 7
  dnf:
    name:
      - python2-psycopg2
      - libselinux-python
      - make
      - systemd-libs
      - systemd-devel
      - devtoolset-9-gcc
      - devtoolset-9-gcc-c++
      - devtoolset-9-binutils
      - tcl
    state: present
  when:
    - ansible_distribution_major_version|int == 7
    - dnf_binary.stat.exists

- name: centos_prerequisites | add specific entry for scl into /etc/profile
  lineinfile:
    path: '/etc/profile'
    regexp: 'source /opt/rh/devtoolset-9/enable'
    line: 'source /opt/rh/devtoolset-9/enable'
    backup: yes

- name: centos_prerequisites | switch selinux to permissive
  selinux:
    state: disabled
